### ISSUE TITLE
Need insight, please

### ISSUE THREAD

**Issue by Daemach** [coldfumonkeh/oauth2server#1]
I'm trying to use your great work to do oauth with amazon alexa smarthome skill account linking.  I got as far as generating the authcode, but I don't know where to get the redirectURI or what to do with the authcode once I have created it.  Can you please give me some insight in how best to proceed?

**Comment by coldfumonkeh** [comment]
Hi @Daemach. It all depends on how you're using the oauth process and which oauth server you are using. The redirect URI is something that you need to provide to this component, and it is a URL that you have registered with the oauth2 server you are using.

This isn't an issue with the component itself, so I'm closing this issue down, but feel free to reach out to me on twitter with details of what you're using and I can try and help point you in the right direction.

**Comment by Daemach** [comment]
I'm one of the few that doesn't use twitter unfortunately - any chance you use slack or could offer advice via email?  I'm daemach@gmail.com if that works.  

Just need pointing in the right direction.  I'm trying to be an oauth server to link alexa to my user database - thought that's what this component did since you have another component for the client side.  More info here:  https://developer.amazon.com/docs/account-linking/account-linking-for-sh-and-other.html

**Comment by coldfumonkeh** [comment]
This component is a helper CFC to allow you to get an access token for the user when they click a "Login with X" button in your web app. It will only return the access token that you need; after that, you would need to reference whichever API the access token relates to to get customer information etc.

After a quick look at the link you sent, this may be helpful for you to read: https://developer.amazon.com/docs/login-with-amazon/web-docs.html

**Comment by Daemach** [comment]
Ahh.  Well, I appreciate your being willing to offer advice anyway.  I am not looking to add LWA/google/facebook to my site right now, though I likely will at some point.  I need to link alexa to the accounts in my system so that when someone says "alexa please turn the lights on", the alexa system can pass a bearer token to my system along with an endpointID and that instruction so I can flip the switch for the right user.
